name: Build PRs
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Plugin
        run: make build-docker

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugin-binaries
          path: releases
